name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./docs

env:
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run build
      - run: npm run deploy
